# -*- coding: utf-8 -*-
"""EBAC_caderno-base.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1muN88b-XPsiJnti_a_hKU1zUIHMQuDUJ
"""

# Calculadora para dois números
numero1 = float(input("Digite o primeiro número: "))
numero2 = float(input("Digite o segundo número: "))

operação = str(input("Digite a operação (+, -, *, /): "))

if operação == "+":
  resultado = numero1 + numero2
elif operação == "-":
  resultado = numero1 - numero2
elif operação == "*":
    resultado = numero1 * numero2
elif operação == "/":
    resultado = numero1 / numero2

print(resultado)